// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "7e3a6a0a-50f5-47e5-a29f-ee54d3b5a658";

const char SSID[]               = "************";    // Network SSID (name)
const char PASS[]               = "**********";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "RhXPs5mA#aaZHYs#KQ#nPtcbK";    // Secret device password

void onLumensChange();
void onIluminacaoChange();
void onQuartoChange();

float Lumens;
int Iluminacao;
bool Quarto;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(Lumens, READWRITE, ON_CHANGE, onLumensChange);
  ArduinoCloud.addProperty(Iluminacao, READWRITE, ON_CHANGE, onIluminacaoChange);
  ArduinoCloud.addProperty(Quarto, READWRITE, ON_CHANGE, onQuartoChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
